### ISSUE TITLE
Navigation item not getting activated

### ISSUE THREAD

**Issue by SutirthaSaha** [dsc712/DCS-WEB#2] opened 2021-12-16 10:08 UTC
**Describe the bug**
On click of any item in the navigation menu, the item is not getting activated

**To Reproduce**
Click on any navigation item menu

**Expected behavior**
The navigation item clicked should have been activated

**Comment by dsc712** [comment] 2021-12-16 10:11
I can reproduce the issue. Please someone pick this up.

**Comment by PragnaDas** [comment] 2021-12-16 10:12
I'm taking this up.

**Comment by dsc712** [comment] 2021-12-16 10:25
Fix is tested and it is working properly. Thanks.

**Comment by dsc712** [comment] 2021-12-16 10:38
@SutirthaSaha @PragnaDas Looks like something is wrong with active menu. Home link is not getting active.

**Comment by SutirthaSaha** [comment] 2021-12-16 10:41
looking into it!

**Comment by dsc712** [comment] 2021-12-16 10:52
Closing this issue as it is fixed in #7

**Closed as completed by dsc712** 2021-12-16 10:52 UTC
Labels: bug
